### ISSUE TITLE
Where is nuget package?

### ISSUE THREAD

**Issue by sekulicb** [YoussefSell/Result.Net#5]
Hi. When typing "Results.Net" into VS2022, yields no match result for your library as you can see in the image below

![image](https://github.com/YoussefSell/Result.Net/assets/20758693/d73f0ce7-97d3-4214-9494-4d123182f5c9)

**Comment by YoussefSell** [comment]
look for "Result.Net" not "Results.Net"

**Comment by sekulicb** [comment]
My bad, looks like I was tired 😄
